### ISSUE TITLE
Add lower-granularity sensing

### ISSUE THREAD

**Issue by jeremybz** [jeremybz/sds011_exporter#1]
According to the manufacturer, lifespan is 8000 hours. http://inovafitness.com/en/a/chanpinzhongxin/95.html

Current default of 1 qps is probably unnecessarily fine.  Add options to query every user-defined interval.

**Comment by Ezekiel69a** [comment]
Frikkin´ lazers man! Be good if they sensors were more like 5$/EUR ea.
